Repository ExceptAnyone/SSAP-IDE-FrontEnd, pull requests merged in 2023-10, with the labels that each got.

#57 회원가입 서버 통신 및 컨테이너 생성,저장,삭제하기 기능 구현
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/PrivateRoute.jsx
  front/src/components/footer/Footer.jsx
  front/src/components/form/LoginForm.jsx
  front/src/components/form/SignUpForm.jsx
  front/src/components/header/Header.css
  front/src/components/header/Header.jsx
  front/src/components/header/LogoutButton.jsx
  front/src/components/header/ProfileIcon.jsx
  front/src/cookie/cookieUtils.jsx
  front/src/index.js
  front/src/page/createContainer/CreateContainerPage.jsx
  front/src/page/editSignupPage/EditSignupPage.css
  front/src/page/editSignupPage/EditSignupPage.jsx
  front/src/page/editcontainer/EditContainerPage.jsx
  front/src/page/loginpage/LoginPage.css
  front/src/page/loginpage/LoginPage.jsx
  front/src/page/loginpage/Test.jsx
  front/src/page/main/LoginForm.jsx
  front/src/page/main/MainPage.css
  front/src/page/main/MainPage.jsx
  front/src/page/main/Test.jsx
  front/src/page/signup/Form.jsx
  front/src/page/signup/SignupPage.css
  front/src/page/signup/SignupPage.jsx
  front/src/redux/authSlice.jsx
  front/src/redux/store.jsx
Labels: 💡 기능, 🛠️ 리팩토링

#58 채팅 알림 기능 및 배포 서버 연결
  .eslintrc.json
  front/package-lock.json
  front/package.json
  front/src/api/chatAPI.js
  front/src/components/chat/Chat.jsx
  front/src/components/chat/chat.scss
  front/src/components/chat/chatUserList/ChatUserList.jsx
  front/src/page/ide/IdePage.jsx
Labels: 💡 기능, 🛠️ 리팩토링

#68 3번째 머지 2
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/form/LoginForm.jsx
  front/src/components/form/SignUpForm.jsx
  front/src/components/header/Header.jsx
  front/src/components/header/LogoutButton.jsx
  front/src/components/header/ProfileIcon.jsx
  front/src/index.js
  front/src/page/createContainer/CreateContainerPage.jsx
  front/src/page/editSignupPage/EditSignupPage.jsx
  front/src/page/editcontainer/EditContainerPage.jsx
  front/src/page/loginpage/LoginPage.jsx
  front/src/page/main/MainPage.jsx
  front/src/page/main/Test.jsx
  front/src/page/page.css
  front/src/page/signup/SignupPage.jsx
  front/src/redux/authSlice.jsx
  front/src/redux/store.jsx
Labels: 💡 기능

#69 ide 3번째 머지
  front/config-overrides.js
  front/package-lock.json
  front/package.json
  front/src/api/ideAPI/createFileAPI.jsx
  front/src/api/ideAPI/createFolderAPI.jsx
  front/src/api/ideAPI/deleteFileAPI.jsx
  front/src/api/ideAPI/deleteFolderAPI.jsx
  front/src/api/ideAPI/folderEditAPI.jsx
  front/src/components/ide/ideUI/header/file/MenuBarComponent.jsx
  front/src/components/ide/ideUI/header/file/useFileAction.jsx
  front/src/components/ide/ideUI/sideBar/Sidebar.jsx
  front/src/components/ide/ideUI/sideBar/customNode/CustomNode.jsx
Labels: 💡 기능

#71 3번째 채팅 merge
  front/package-lock.json
  front/package.json
  front/src/api/chatAPI.js
  front/src/components/chat/Chat.jsx
  front/src/components/chat/chat.scss
  front/src/components/chat/chatUserList/ChatUserList.jsx
  front/src/page/ide/IdePage.jsx
Labels: 💡 기능

#72 Ide css 처리를 위한 머지
  front/src/api/ideAPI/createFolderAPI.jsx
  front/src/components/ide/codeEditor/CodeEditor.css
  front/src/components/ide/ideUI/header/file/useFileAction.jsx
  front/src/components/ide/ideUI/sideBar/Sidebar.css
  front/src/components/ide/ideUI/sideBar/Sidebar.jsx
  front/src/components/ide/ideUI/sideBar/customNode/CustomNode.jsx
  front/src/components/ide/layout/Layout.css
  front/src/components/ide/layout/Layout.jsx
  front/src/page/ide/IdePage.css
  front/src/page/ide/IdePage.jsx
Labels: 🙏 헬프미

#73 css작업을 위한 머지
  front/src/components/header/Header.jsx
  front/src/page/createContainer/CreateContainerPage.jsx
  front/src/page/editcontainer/EditContainerPage.jsx
  front/src/page/main/MainPage.jsx
  front/src/page/main/Test.jsx
  git reflog
Labels: 💡 기능
